#
# Constantin Knizhnik
# Moscow Software Center
# BGI for Windows
#

DEFINES = 
CC = bcc32 -P

# Debug
#CFLAGS=-c -v  $(DEFINES)

# Optimize
CFLAGS=-c -O2 -v $(DEFINES)

LD = cl
LDOPT = 
#LDOPT =

AR = tlib

LIB = ..\winbgi.lib


all: $(LIB)

winbgi.obj: winbgi.cxx graphics.h
	$(CC) $(CFLAGS) -c winbgi.cxx

$(LIB): winbgi.obj
	-del $(LIB)
	$(AR) $(ARFLAGS) $(LIB) +winbgi.obj


clean:
        del *.obj
        del *.ilk
        del *.zip
	del *.*~

